from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow,arrPercent,arrStatistical):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 200, 1000, 400))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(190, 50, 661, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setItem(1, 0, item)        
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)       
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)       
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)        
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font) 
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font) 
        self.tableWidget.setItem(5, 4, item)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font) 
        self.label = QtWidgets.QLabel(self.frame)
        
        self.label.setGeometry(QtCore.QRect(190, 10, 441, 31))
        
        self.label.setObjectName("label")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(235, 61, 477, 106))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(1, 2, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 93, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow,arrPercent,arrStatistical)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow,arrPercent,arrStatistical):
        min = -1
        max = 0
        for i in range(len(arrStatistical)):
            for j in range(len(arrStatistical[i])):
                if i != j:
                    if min < arrStatistical[i][j]:
                        min = arrStatistical[i][j]
                else:
                    if max < arrStatistical[i][j]:
                        max = arrStatistical[i][j]
        maxpercent = -1 
        for i in arrPercent:
            if i > maxpercent:
                maxpercent = i
        font = QtGui.QFont()
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "/a/"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "/e/"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "/i/"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "/o/"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "/u/"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "/a/"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "/e/"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "/i/"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "/o/"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "/u/"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", str(arrStatistical[0][0])))        
        if max == arrStatistical[0][0]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", str(arrStatistical[0][1])))
        if min == arrStatistical[0][1]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", str(arrStatistical[0][2])))
        if min == arrStatistical[0][2]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", str(arrStatistical[0][3])))
        if min == arrStatistical[0][3]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", str(arrStatistical[0][4])))
        if min == arrStatistical[0][4]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", str(arrStatistical[1][0])))
        if min == arrStatistical[1][0]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", str(arrStatistical[1][1])))
        if max == arrStatistical[1][1]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", str(arrStatistical[1][2])))
        if min == arrStatistical[1][2]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", str(arrStatistical[1][3])))
        if min == arrStatistical[1][3]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", str(arrStatistical[1][4])))
        if min == arrStatistical[1][4]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", str(arrStatistical[2][0])))
        if min == arrStatistical[2][0]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", str(arrStatistical[2][1])))
        if min == arrStatistical[2][1]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", str(arrStatistical[2][2])))
        if max == arrStatistical[2][2]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", str(arrStatistical[2][3])))
        if min == arrStatistical[2][3]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", str(arrStatistical[2][4])))
        if min == arrStatistical[2][4]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", str(arrStatistical[3][0])))
        if min == arrStatistical[3][0]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", str(arrStatistical[3][1])))
        if min == arrStatistical[3][1]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", str(arrStatistical[3][2])))
        if min == arrStatistical[3][2]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", str(arrStatistical[3][3])))
        if max == arrStatistical[3][3]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", str(arrStatistical[3][4])))
        if min == arrStatistical[3][4]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", str(arrStatistical[4][0])))
        if min == arrStatistical[4][0]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", str(arrStatistical[4][1])))
        if min == arrStatistical[4][1]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", str(arrStatistical[4][2])))
        if min == arrStatistical[4][2]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", str(arrStatistical[4][3])))
        if min == arrStatistical[4][3]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", str(arrStatistical[4][4])))
        if max == arrStatistical[4][4]:
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Ma trận nhầm lẫn với N_MFCC = 13</span></p></body></html>"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Độ chính xác"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N_MFCC = 13"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "N_MFCC = 26"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "N_MFCC = 39"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", f"{str(arrPercent[0])}%"))
        if maxpercent == arrPercent[0]:
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", f"{str(arrPercent[1])}%"))
        if maxpercent == arrPercent[1]:
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        item = self.tableWidget_2.item(1, 2)
        
        item.setText(_translate("MainWindow", f"{str(arrPercent[2])}%"))
        if maxpercent == arrPercent[2]:
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Quay lại"))
